# Exception is a erro handaling so it is problam solving
sourav = int(input("Give me a number: "))

try: # try and axcept that is so erro handaling managment
    print(20/sourav)
except Exception as asha:
    print(f"sorry there is an asha as {asha}")
else:
    print("There is run by good code")
finally:
    print("I will run no matter what!")

print("sourav is very fucking man😁")

